services:
  micro-bucket:
    image: python:3.11-slim
    container_name: micro-bucket
    ports:
      - "8080:8080"
    volumes:
      - ./packages:/packages
    working_dir: /packages
    command: python3 -m http.server 8080
