apiVersion: v1
kind: policy
spec:
  name: macOS Firewall Enabled and Stealth Mode On
  query: |
    SELECT 1
    FROM alf
    WHERE global_state = 1
      AND stealth_enabled = 1;
  platform: darwin
---
apiVersion: v1
kind: policy
spec:
  name: saltyMacs state.json exists
  query: |
    SELECT 1
    FROM file
    WHERE path = '/usr/local/saltymacs/state.json';
  platform: darwin

apiVersion: v1
kind: policy
spec:
  name: Apparency installed
  query: |
    SELECT 1
    FROM apps
    WHERE name = 'Apparency';
  platform: darwin
