jenkins:
  systemMessage: "saltyFleet Jenkins"

  numExecutors: 2

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: "http://localhost:8080/"

jobs:
  - script: >
      pipelineJob('saltyFleet-ci') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/mrbrown89/saltyFleet.git')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
